codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "70...90"

  status:
    project: yes
    patch: yes
    changes: no

  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: null
        only_pulls: false
        branches: null
        flags: null
        paths: null

  ignore:
    - "tests/**/*"
    - "tests/.*"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
